spring.application.name=email

server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/ms_email?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuração do CloudAMQP/RabbitMQ 
spring.rabbitmq.addresses=amqps://qxtaghst:xZbWOhaKY8Z-H3a3M2dQGfLzUtJsiXLl@beaver.rmq.cloudamqp.com/qxtaghst
broker.queue.email.name=default.email

# Configuração do SMTP do Gmail para envio de e-mail real
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pedroenrico61@gmail.com
spring.mail.password=tvqylvpajadoieml
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true